<a href="https://colab.research.google.com/github/anilkumar4274/aiassignments/blob/master/KNN%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from npknn import NonparametricKNN

In [0]:
def L1(pred,true):
    loss = np.abs(pred-true)
    return loss.mean()

In [0]:
L2(np.array([[2,2,2],[3,3,3]]),np.array([[3,3,3],[6,6,6]]))

5.0

In [0]:
def L1(pred,true):
    loss = np.abs(pred-true)
    return loss.mean()

In [0]:
L1(np.array([[2,2,2],[3,3,3]]),np.array([[3,3,3],[6,6,6]]))

2.0

In [0]:
type(L1(-20,10))

numpy.float64

In [0]:
def SMAPE(pred,true):
    loss = np.abs((pred-true)/(pred+true))
    return loss.mean()

In [0]:
aa={'a':11,'b':12,'c':13}

In [0]:
for i in aa.items():
    print(i[0])

a
b
c


In [0]:
if loss in ['L1','L2','SMAPE']:
    loss = {'L1':L1,'L2':L2,'SMAPE':SMAPE}[loss]
    print(loss)

In [0]:
#Data
train = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
target = np.array([1,2,3,7,17])
test = np.array([[3,3,3],[6,6,6]])

In [0]:
#Initialize model
model = NonparametricKNN(n_neighbors=3,loss='L2')
#Train
model.fit(train,target)
#Predict
model.predict(test)

array([4., 9.])

In [0]:
#When we use L2 loss, we get exactly the same result as the KNN regressor in sklearn.
from sklearn.neighbors import KNeighborsRegressor
model = NonparametricKNN(n_neighbors=3)
model.fit(train,target)
model.predict(test)

array([4., 9.])

In [0]:
#When we use other loss, predictions could be different.
model = NonparametricKNN(n_neighbors=3,loss='L1')
model.fit(train,target)
model.predict(test)

array([3, 7])

In [0]:
#Customized loss
def loss(pred,true):#Loss function should take two numpy arrays as inputs...
    result = np.power(pred-true,4)
    return result.mean()#and return a scalar.
model = NonparametricKNN(n_neighbors=3,loss=loss)#Pass the loss function as argument.
model.fit(train,target)
model.predict(test)

array([4., 9.])