<a href="https://colab.research.google.com/github/anilkumar4274/aiassignments/blob/sharath/pickle_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
What is pickle module and why do we use this module in machine learning?
pickle module is a python module used in machine learning to save the model and used to re-train it later.

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
df=pd.read_csv('homeprices.csv')

In [0]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [0]:
from sklearn.linear_model import LinearRegression
model=LinearRegression().fit(df[['area']],df['price'])

In [0]:
model.coef_

array([135.78767123])

# import pickle module

In [0]:
import pickle

# save the model

In [0]:
with open('pickle_model','wb') as file:
    pickle.dump(model,file)

# load the model

In [0]:
with open('pickle_model','rb') as file:
    ml=pickle.load(file)

In [0]:
ml.coef_

array([135.78767123])

# Joblib model

In [0]:
from sklearn.externals import joblib

# Save the model

In [0]:
joblib.dump(model,'joblib_model')

['joblib_model']

# Load the Model

In [0]:
jl=joblib.load('joblib_model')

In [0]:
jl.coef_

array([135.78767123])

In [0]:
df.shape

(5, 2)